AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  BraynDevHello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.serverless.Handler
      Runtime: java8
      CodeUri: build/libs/hello-dev-all.jar
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: Brayn
  Brayn:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /:
            any:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BraynDevHello.Arn}/invocations
              responses: {}
  BraynDevHelloLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - BraynDevHello
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: BraynDevHello
      Principal: apigateway.amazonaws.com
